inherit_from: ../.rubocop.yml

# This will possibly be removed when all cops are passing;
# for now I'd like these to be easy to see.
RSpec/Focus:
  Severity: warning

Style/MixinUsage:
  Exclude:
    - support/helper_includes.rb

Style/SignalException:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

################################################################################

RSpec/ContextWording:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/NoExpectationExample:
  Enabled: false

RSpec/SortMetadata:
  Enabled: false

################################################################################

Capybara/SpecificFinders:
  Enabled: false
