inherit_from: ../.rubocop.yml

require:
  - rubocop-rspec
  - rubocop-capybara

# This will possibly be removed when all cops are passing; for now I'd like
# these to be easy to see.
RSpec/Focus:
  Severity: warning

Lint/AmbiguousBlockAssociation:
  Enabled: false
