runOnLoad(() => {
    M.Autocomplete.init(document.querySelectorAll(".autocomplete"), { data: {
        "Bulbasaur": "/images/sprites/001.png",
        "Ivysaur": "/images/sprites/002.png",
        "Venusaur": "/images/sprites/003.png",
        "Charmander": "/images/sprites/004.png",
        "Charmeleon": "/images/sprites/005.png",
        "Charizard": "/images/sprites/006.png",
        "Squirtle": "/images/sprites/007.png",
        "Wartortle": "/images/sprites/008.png",
        "Blastoise": "/images/sprites/009.png",
        "Caterpie": "/images/sprites/010.png",
        "Metapod": "/images/sprites/011.png",
        "Butterfree": "/images/sprites/012.png",
        "Weedle": "/images/sprites/013.png",
        "Kakuna": "/images/sprites/014.png",
        "Beedrill": "/images/sprites/015.png",
        "Pidgey": "/images/sprites/016.png",
        "Pidgeotto": "/images/sprites/017.png",
        "Pidgeot": "/images/sprites/018.png",
        "Rattata": "/images/sprites/019.png",
        "Rattata (Alolan)": "/images/sprites/019-a.png",
        "Raticate": "/images/sprites/020.png",
        "Raticate (Alolan)": "/images/sprites/020-a.png",
        "Spearow": "/images/sprites/021.png",
        "Fearow": "/images/sprites/022.png",
        "Ekans": "/images/sprites/023.png",
        "Arbok": "/images/sprites/024.png",
        "Pikachu": "/images/sprites/025.png",
        "Raichu": "/images/sprites/026.png",
        "Raichu (Alolan)": "/images/sprites/026-a.png",
        "Sandshrew": "/images/sprites/027.png",
        "Sandshrew (Alolan)": "/images/sprites/027-a.png",
        "Sandslash": "/images/sprites/028.png",
        "Sandslash (Alolan)": "/images/sprites/028-a.png",
        "Nidoran♀": "/images/sprites/029.png",
        "Nidorina": "/images/sprites/030.png",
        "Nidoqueen": "/images/sprites/031.png",
        "Nidoran♂": "/images/sprites/032.png",
        "Nidorino": "/images/sprites/033.png",
        "Nidoking": "/images/sprites/034.png",
        "Clefairy": "/images/sprites/035.png",
        "Clefable": "/images/sprites/036.png",
        "Vulpix": "/images/sprites/037.png",
        "Vulpix (Alolan)": "/images/sprites/037-a.png",
        "Ninetales": "/images/sprites/038.png",
        "Ninetales (Alolan)": "/images/sprites/038-a.png",
        "Jigglypuff": "/images/sprites/039.png",
        "Wigglytuff": "/images/sprites/040.png",
        "Zubat": "/images/sprites/041.png",
        "Golbat": "/images/sprites/042.png",
        "Oddish": "/images/sprites/043.png",
        "Gloom": "/images/sprites/044.png",
        "Vileplume": "/images/sprites/045.png",
        "Paras": "/images/sprites/046.png",
        "Parasect": "/images/sprites/047.png",
        "Venonat": "/images/sprites/048.png",
        "Venomoth": "/images/sprites/049.png",
        "Diglett": "/images/sprites/050.png",
        "Diglett (Alolan)": "/images/sprites/050-a.png",
        "Dugtrio": "/images/sprites/051.png",
        "Dugtrio (Alolan)": "/images/sprites/051-a.png",
        "Meowth": "/images/sprites/052.png",
        "Meowth (Alolan)": "/images/sprites/052-a.png",
        "Meowth (Galarian)": "/images/sprites/052-g.png",
        "Persian": "/images/sprites/053.png",
        "Persian (Alolan)": "/images/sprites/053-a.png",
        "Psyduck": "/images/sprites/054.png",
        "Golduck": "/images/sprites/055.png",
        "Mankey": "/images/sprites/056.png",
        "Primeape": "/images/sprites/057.png",
        "Growlithe": "/images/sprites/058.png",
        "Growlithe (Hisuian)": "/images/sprites/058-h.png",
        "Arcanine": "/images/sprites/059.png",
        "Arcanine (Hisuian)": "/images/sprites/059-h.png",
        "Poliwag": "/images/sprites/060.png",
        "Poliwhirl": "/images/sprites/061.png",
        "Poliwrath": "/images/sprites/062.png",
        "Abra": "/images/sprites/063.png",
        "Kadabra": "/images/sprites/064.png",
        "Alakazam": "/images/sprites/065.png",
        "Machop": "/images/sprites/066.png",
        "Machoke": "/images/sprites/067.png",
        "Machamp": "/images/sprites/068.png",
        "Bellsprout": "/images/sprites/069.png",
        "Weepinbell": "/images/sprites/070.png",
        "Victreebel": "/images/sprites/071.png",
        "Tentacool": "/images/sprites/072.png",
        "Tentacruel": "/images/sprites/073.png",
        "Geodude": "/images/sprites/074.png",
        "Geodude (Alolan)": "/images/sprites/074-a.png",
        "Graveler": "/images/sprites/075.png",
        "Graveler (Alolan)": "/images/sprites/075-a.png",
        "Golem": "/images/sprites/076.png",
        "Golem (Alolan)": "/images/sprites/076-a.png",
        "Ponyta": "/images/sprites/077.png",
        "Ponyta (Galarian)": "/images/sprites/077-g.png",
        "Rapidash": "/images/sprites/078.png",
        "Rapidash (Galarian)": "/images/sprites/078-g.png",
        "Slowpoke": "/images/sprites/079.png",
        "Slowpoke (Galarian)": "/images/sprites/079-g.png",
        "Slowbro": "/images/sprites/080.png",
        "Slowbro (Galarian)": "/images/sprites/080-g.png",
        "Magnemite": "/images/sprites/081.png",
        "Magneton": "/images/sprites/082.png",
        "Farfetchd": "/images/sprites/083.png",
        "Farfetchd (Galarian)": "/images/sprites/083-g.png",
        "Doduo": "/images/sprites/084.png",
        "Dodrio": "/images/sprites/085.png",
        "Seel": "/images/sprites/086.png",
        "Dewgong": "/images/sprites/087.png",
        "Grimer": "/images/sprites/088.png",
        "Grimer (Alolan)": "/images/sprites/088-a.png",
        "Muk": "/images/sprites/089.png",
        "Muk (Alolan)": "/images/sprites/089-a.png",
        "Shellder": "/images/sprites/090.png",
        "Cloyster": "/images/sprites/091.png",
        "Gastly": "/images/sprites/092.png",
        "Haunter": "/images/sprites/093.png",
        "Gengar": "/images/sprites/094.png",
        "Onix": "/images/sprites/095.png",
        "Drowzee": "/images/sprites/096.png",
        "Hypno": "/images/sprites/097.png",
        "Krabby": "/images/sprites/098.png",
        "Kingler": "/images/sprites/099.png",
        "Voltorb": "/images/sprites/100.png",
        "Voltorb (Hisuian)": "/images/sprites/100-h.png",
        "Electrode": "/images/sprites/101.png",
        "Electrode (Hisuian)": "/images/sprites/101-h.png",
        "Exeggcute": "/images/sprites/102.png",
        "Exeggutor": "/images/sprites/103.png",
        "Exeggutor (Alolan)": "/images/sprites/103-a.png",
        "Cubone": "/images/sprites/104.png",
        "Marowak": "/images/sprites/105.png",
        "Marowak (Alolan)": "/images/sprites/105-a.png",
        "Hitmonlee": "/images/sprites/106.png",
        "Hitmonchan": "/images/sprites/107.png",
        "Lickitung": "/images/sprites/108.png",
        "Koffing": "/images/sprites/109.png",
        "Weezing": "/images/sprites/110.png",
        "Weezing (Galarian)": "/images/sprites/110-g.png",
        "Rhyhorn": "/images/sprites/111.png",
        "Rhydon": "/images/sprites/112.png",
        "Chansey": "/images/sprites/113.png",
        "Tangela": "/images/sprites/114.png",
        "Kangaskhan": "/images/sprites/115.png",
        "Horsea": "/images/sprites/116.png",
        "Seadra": "/images/sprites/117.png",
        "Goldeen": "/images/sprites/118.png",
        "Seaking": "/images/sprites/119.png",
        "Staryu": "/images/sprites/120.png",
        "Starmie": "/images/sprites/121.png",
        "Mr. Mime": "/images/sprites/122.png",
        "Mr. Mime (Galarian)": "/images/sprites/122-g.png",
        "Scyther": "/images/sprites/123.png",
        "Jynx": "/images/sprites/124.png",
        "Electabuzz": "/images/sprites/125.png",
        "Magmar": "/images/sprites/126.png",
        "Pinsir": "/images/sprites/127.png",
        "Tauros": "/images/sprites/128.png",
        "Tauros (Combat)": "/images/sprites/128-p.png",
        "Tauros (Blaze)": "/images/sprites/128-b.png",
        "Tauros (Aqua)": "/images/sprites/128-a.png",
        "Magikarp": "/images/sprites/129.png",
        "Gyarados": "/images/sprites/130.png",
        "Lapras": "/images/sprites/131.png",
        "Ditto": "/images/sprites/132.png",
        "Eevee": "/images/sprites/133.png",
        "Vaporeon": "/images/sprites/134.png",
        "Jolteon": "/images/sprites/135.png",
        "Flareon": "/images/sprites/136.png",
        "Porygon": "/images/sprites/137.png",
        "Omanyte": "/images/sprites/138.png",
        "Omastar": "/images/sprites/139.png",
        "Kabuto": "/images/sprites/140.png",
        "Kabutops": "/images/sprites/141.png",
        "Aerodactyl": "/images/sprites/142.png",
        "Snorlax": "/images/sprites/143.png",
        "Articuno": "/images/sprites/144.png",
        "Articuno (Galarian)": "/images/sprites/144-g.png",
        "Zapdos": "/images/sprites/145.png",
        "Zapdos (Galarian)": "/images/sprites/145-g.png",
        "Moltres": "/images/sprites/146.png",
        "Moltres (Galarian)": "/images/sprites/146-g.png",
        "Dratini": "/images/sprites/147.png",
        "Dragonair": "/images/sprites/148.png",
        "Dragonite": "/images/sprites/149.png",
        "Mewtwo": "/images/sprites/150.png",
        "Mew": "/images/sprites/151.png",
        "Chikorita": "/images/sprites/152.png",
        "Bayleef": "/images/sprites/153.png",
        "Meganium": "/images/sprites/154.png",
        "Cyndaquil": "/images/sprites/155.png",
        "Quilava": "/images/sprites/156.png",
        "Typhlosion": "/images/sprites/157.png",
        "Typhlosion (Hisuian)": "/images/sprites/157-h.png",
        "Totodile": "/images/sprites/158.png",
        "Croconaw": "/images/sprites/159.png",
        "Feraligatr": "/images/sprites/160.png",
        "Sentret": "/images/sprites/161.png",
        "Furret": "/images/sprites/162.png",
        "Hoothoot": "/images/sprites/163.png",
        "Noctowl": "/images/sprites/164.png",
        "Ledyba": "/images/sprites/165.png",
        "Ledian": "/images/sprites/166.png",
        "Spinarak": "/images/sprites/167.png",
        "Ariados": "/images/sprites/168.png",
        "Crobat": "/images/sprites/169.png",
        "Chinchou": "/images/sprites/170.png",
        "Lanturn": "/images/sprites/171.png",
        "Pichu": "/images/sprites/172.png",
        "Cleffa": "/images/sprites/173.png",
        "Igglybuff": "/images/sprites/174.png",
        "Togepi": "/images/sprites/175.png",
        "Togetic": "/images/sprites/176.png",
        "Natu": "/images/sprites/177.png",
        "Xatu": "/images/sprites/178.png",
        "Mareep": "/images/sprites/179.png",
        "Flaaffy": "/images/sprites/180.png",
        "Ampharos": "/images/sprites/181.png",
        "Bellossom": "/images/sprites/182.png",
        "Marill": "/images/sprites/183.png",
        "Azumarill": "/images/sprites/184.png",
        "Sudowoodo": "/images/sprites/185.png",
        "Politoed": "/images/sprites/186.png",
        "Hoppip": "/images/sprites/187.png",
        "Skiploom": "/images/sprites/188.png",
        "Jumpluff": "/images/sprites/189.png",
        "Aipom": "/images/sprites/190.png",
        "Sunkern": "/images/sprites/191.png",
        "Sunflora": "/images/sprites/192.png",
        "Yanma": "/images/sprites/193.png",
        "Wooper": "/images/sprites/194.png",
        "Wooper (Paldean)": "/images/sprites/194-p.png",
        "Quagsire": "/images/sprites/195.png",
        "Espeon": "/images/sprites/196.png",
        "Umbreon": "/images/sprites/197.png",
        "Murkrow": "/images/sprites/198.png",
        "Slowking": "/images/sprites/199.png",
        "Slowking (Galarian)": "/images/sprites/199-g.png",
        "Misdreavus": "/images/sprites/200.png",
        "Unown": "/images/sprites/201.png",
        "Wobbuffet": "/images/sprites/202.png",
        "Girafarig": "/images/sprites/203.png",
        "Pineco": "/images/sprites/204.png",
        "Forretress": "/images/sprites/205.png",
        "Dunsparce": "/images/sprites/206.png",
        "Gligar": "/images/sprites/207.png",
        "Steelix": "/images/sprites/208.png",
        "Snubbull": "/images/sprites/209.png",
        "Granbull": "/images/sprites/210.png",
        "Qwilfish": "/images/sprites/211.png",
        "Qwilfish (Hisuian)": "/images/sprites/211-h.png",
        "Scizor": "/images/sprites/212.png",
        "Shuckle": "/images/sprites/213.png",
        "Heracross": "/images/sprites/214.png",
        "Sneasel": "/images/sprites/215.png",
        "Sneasel (Hisuian)": "/images/sprites/215-h.png",
        "Teddiursa": "/images/sprites/216.png",
        "Ursaring": "/images/sprites/217.png",
        "Slugma": "/images/sprites/218.png",
        "Magcargo": "/images/sprites/219.png",
        "Swinub": "/images/sprites/220.png",
        "Piloswine": "/images/sprites/221.png",
        "Corsola": "/images/sprites/222.png",
        "Corsola (Galarian)": "/images/sprites/222-g.png",
        "Remoraid": "/images/sprites/223.png",
        "Octillery": "/images/sprites/224.png",
        "Delibird": "/images/sprites/225.png",
        "Mantine": "/images/sprites/226.png",
        "Skarmory": "/images/sprites/227.png",
        "Houndour": "/images/sprites/228.png",
        "Houndoom": "/images/sprites/229.png",
        "Kingdra": "/images/sprites/230.png",
        "Phanpy": "/images/sprites/231.png",
        "Donphan": "/images/sprites/232.png",
        "Porygon2": "/images/sprites/233.png",
        "Stantler": "/images/sprites/234.png",
        "Smeargle": "/images/sprites/235.png",
        "Tyrogue": "/images/sprites/236.png",
        "Hitmontop": "/images/sprites/237.png",
        "Smoochum": "/images/sprites/238.png",
        "Elekid": "/images/sprites/239.png",
        "Magby": "/images/sprites/240.png",
        "Miltank": "/images/sprites/241.png",
        "Blissey": "/images/sprites/242.png",
        "Raikou": "/images/sprites/243.png",
        "Entei": "/images/sprites/244.png",
        "Suicune": "/images/sprites/245.png",
        "Larvitar": "/images/sprites/246.png",
        "Pupitar": "/images/sprites/247.png",
        "Tyranitar": "/images/sprites/248.png",
        "Lugia": "/images/sprites/249.png",
        "Ho-Oh": "/images/sprites/250.png",
        "Celebi": "/images/sprites/251.png",
        "Treecko": "/images/sprites/252.png",
        "Grovyle": "/images/sprites/253.png",
        "Sceptile": "/images/sprites/254.png",
        "Torchic": "/images/sprites/255.png",
        "Combusken": "/images/sprites/256.png",
        "Blaziken": "/images/sprites/257.png",
        "Mudkip": "/images/sprites/258.png",
        "Marshtomp": "/images/sprites/259.png",
        "Swampert": "/images/sprites/260.png",
        "Poochyena": "/images/sprites/261.png",
        "Mightyena": "/images/sprites/262.png",
        "Zigzagoon": "/images/sprites/263.png",
        "Zigzagoon (Galarian)": "/images/sprites/263-g.png",
        "Linoone": "/images/sprites/264.png",
        "Linoone (Galarian)": "/images/sprites/264-g.png",
        "Wurmple": "/images/sprites/265.png",
        "Silcoon": "/images/sprites/266.png",
        "Beautifly": "/images/sprites/267.png",
        "Cascoon": "/images/sprites/268.png",
        "Dustox": "/images/sprites/269.png",
        "Lotad": "/images/sprites/270.png",
        "Lombre": "/images/sprites/271.png",
        "Ludicolo": "/images/sprites/272.png",
        "Seedot": "/images/sprites/273.png",
        "Nuzleaf": "/images/sprites/274.png",
        "Shiftry": "/images/sprites/275.png",
        "Taillow": "/images/sprites/276.png",
        "Swellow": "/images/sprites/277.png",
        "Wingull": "/images/sprites/278.png",
        "Pelipper": "/images/sprites/279.png",
        "Ralts": "/images/sprites/280.png",
        "Kirlia": "/images/sprites/281.png",
        "Gardevoir": "/images/sprites/282.png",
        "Surskit": "/images/sprites/283.png",
        "Masquerain": "/images/sprites/284.png",
        "Shroomish": "/images/sprites/285.png",
        "Breloom": "/images/sprites/286.png",
        "Slakoth": "/images/sprites/287.png",
        "Vigoroth": "/images/sprites/288.png",
        "Slaking": "/images/sprites/289.png",
        "Nincada": "/images/sprites/290.png",
        "Ninjask": "/images/sprites/291.png",
        "Shedinja": "/images/sprites/292.png",
        "Whismur": "/images/sprites/293.png",
        "Loudred": "/images/sprites/294.png",
        "Exploud": "/images/sprites/295.png",
        "Makuhita": "/images/sprites/296.png",
        "Hariyama": "/images/sprites/297.png",
        "Azurill": "/images/sprites/298.png",
        "Nosepass": "/images/sprites/299.png",
        "Skitty": "/images/sprites/300.png",
        "Delcatty": "/images/sprites/301.png",
        "Sableye": "/images/sprites/302.png",
        "Mawile": "/images/sprites/303.png",
        "Aron": "/images/sprites/304.png",
        "Lairon": "/images/sprites/305.png",
        "Aggron": "/images/sprites/306.png",
        "Meditite": "/images/sprites/307.png",
        "Medicham": "/images/sprites/308.png",
        "Electrike": "/images/sprites/309.png",
        "Manectric": "/images/sprites/310.png",
        "Plusle": "/images/sprites/311.png",
        "Minun": "/images/sprites/312.png",
        "Volbeat": "/images/sprites/313.png",
        "Illumise": "/images/sprites/314.png",
        "Roselia": "/images/sprites/315.png",
        "Gulpin": "/images/sprites/316.png",
        "Swalot": "/images/sprites/317.png",
        "Carvanha": "/images/sprites/318.png",
        "Sharpedo": "/images/sprites/319.png",
        "Wailmer": "/images/sprites/320.png",
        "Wailord": "/images/sprites/321.png",
        "Numel": "/images/sprites/322.png",
        "Camerupt": "/images/sprites/323.png",
        "Torkoal": "/images/sprites/324.png",
        "Spoink": "/images/sprites/325.png",
        "Grumpig": "/images/sprites/326.png",
        "Spinda": "/images/sprites/327.png",
        "Trapinch": "/images/sprites/328.png",
        "Vibrava": "/images/sprites/329.png",
        "Flygon": "/images/sprites/330.png",
        "Cacnea": "/images/sprites/331.png",
        "Cacturne": "/images/sprites/332.png",
        "Swablu": "/images/sprites/333.png",
        "Altaria": "/images/sprites/334.png",
        "Zangoose": "/images/sprites/335.png",
        "Seviper": "/images/sprites/336.png",
        "Lunatone": "/images/sprites/337.png",
        "Solrock": "/images/sprites/338.png",
        "Barboach": "/images/sprites/339.png",
        "Whiscash": "/images/sprites/340.png",
        "Corphish": "/images/sprites/341.png",
        "Crawdaunt": "/images/sprites/342.png",
        "Baltoy": "/images/sprites/343.png",
        "Claydol": "/images/sprites/344.png",
        "Lileep": "/images/sprites/345.png",
        "Cradily": "/images/sprites/346.png",
        "Anorith": "/images/sprites/347.png",
        "Armaldo": "/images/sprites/348.png",
        "Feebas": "/images/sprites/349.png",
        "Milotic": "/images/sprites/350.png",
        "Castform": "/images/sprites/351.png",
        "Castform (Sunny)": "/images/sprites/351-sun.png",
        "Castform (Rainy)": "/images/sprites/351-r.png",
        "Castform (Snowy)": "/images/sprites/351-sn.png",
        "Kecleon": "/images/sprites/352.png",
        "Shuppet": "/images/sprites/353.png",
        "Banette": "/images/sprites/354.png",
        "Duskull": "/images/sprites/355.png",
        "Dusclops": "/images/sprites/356.png",
        "Tropius": "/images/sprites/357.png",
        "Chimecho": "/images/sprites/358.png",
        "Absol": "/images/sprites/359.png",
        "Wynaut": "/images/sprites/360.png",
        "Snorunt": "/images/sprites/361.png",
        "Glalie": "/images/sprites/362.png",
        "Spheal": "/images/sprites/363.png",
        "Sealeo": "/images/sprites/364.png",
        "Walrein": "/images/sprites/365.png",
        "Clamperl": "/images/sprites/366.png",
        "Huntail": "/images/sprites/367.png",
        "Gorebyss": "/images/sprites/368.png",
        "Relicanth": "/images/sprites/369.png",
        "Luvdisc": "/images/sprites/370.png",
        "Bagon": "/images/sprites/371.png",
        "Shelgon": "/images/sprites/372.png",
        "Salamence": "/images/sprites/373.png",
        "Beldum": "/images/sprites/374.png",
        "Metang": "/images/sprites/375.png",
        "Metagross": "/images/sprites/376.png",
        "Regirock": "/images/sprites/377.png",
        "Regice": "/images/sprites/378.png",
        "Registeel": "/images/sprites/379.png",
        "Latias": "/images/sprites/380.png",
        "Latios": "/images/sprites/381.png",
        "Kyogre": "/images/sprites/382.png",
        "Groudon": "/images/sprites/383.png",
        "Rayquaza": "/images/sprites/384.png",
        "Jirachi": "/images/sprites/385.png",
        "Deoxys": "/images/sprites/386.png",
        "Deoxys (Attack)": "/images/sprites/386-atk.png",
        "Deoxys (Defense)": "/images/sprites/386-def.png",
        "Deoxys (Speed)": "/images/sprites/386-spe.png",
        "Turtwig": "/images/sprites/387.png",
        "Grotle": "/images/sprites/388.png",
        "Torterra": "/images/sprites/389.png",
        "Chimchar": "/images/sprites/390.png",
        "Monferno": "/images/sprites/391.png",
        "Infernape": "/images/sprites/392.png",
        "Piplup": "/images/sprites/393.png",
        "Prinplup": "/images/sprites/394.png",
        "Empoleon": "/images/sprites/395.png",
        "Starly": "/images/sprites/396.png",
        "Staravia": "/images/sprites/397.png",
        "Staraptor": "/images/sprites/398.png",
        "Bidoof": "/images/sprites/399.png",
        "Bibarel": "/images/sprites/400.png",
        "Kricketot": "/images/sprites/401.png",
        "Kricketune": "/images/sprites/402.png",
        "Shinx": "/images/sprites/403.png",
        "Luxio": "/images/sprites/404.png",
        "Luxray": "/images/sprites/405.png",
        "Budew": "/images/sprites/406.png",
        "Roserade": "/images/sprites/407.png",
        "Cranidos": "/images/sprites/408.png",
        "Rampardos": "/images/sprites/409.png",
        "Shieldon": "/images/sprites/410.png",
        "Bastiodon": "/images/sprites/411.png",
        "Burmy (Plant)": "/images/sprites/412-p.png",
        "Burmy (Sandy)": "/images/sprites/412-s.png",
        "Burmy (Trash)": "/images/sprites/412-t.png",
        "Wormadam (Plant)": "/images/sprites/413-p.png",
        "Wormadam (Sandy)": "/images/sprites/413-s.png",
        "Wormadam (Trash)": "/images/sprites/413-t.png",
        "Mothim": "/images/sprites/414.png",
        "Combee": "/images/sprites/415.png",
        "Vespiquen": "/images/sprites/416.png",
        "Pachirisu": "/images/sprites/417.png",
        "Buizel": "/images/sprites/418.png",
        "Floatzel": "/images/sprites/419.png",
        "Cherubi": "/images/sprites/420.png",
        "Cherrim": "/images/sprites/421.png",
        "Shellos": "/images/sprites/422.png",
        "Gastrodon": "/images/sprites/423.png",
        "Ambipom": "/images/sprites/424.png",
        "Drifloon": "/images/sprites/425.png",
        "Drifblim": "/images/sprites/426.png",
        "Buneary": "/images/sprites/427.png",
        "Lopunny": "/images/sprites/428.png",
        "Mismagius": "/images/sprites/429.png",
        "Honchkrow": "/images/sprites/430.png",
        "Glameow": "/images/sprites/431.png",
        "Purugly": "/images/sprites/432.png",
        "Chingling": "/images/sprites/433.png",
        "Stunky": "/images/sprites/434.png",
        "Skuntank": "/images/sprites/435.png",
        "Bronzor": "/images/sprites/436.png",
        "Bronzong": "/images/sprites/437.png",
        "Bonsly": "/images/sprites/438.png",
        "Mime Jr.": "/images/sprites/439.png",
        "Happiny": "/images/sprites/440.png",
        "Chatot": "/images/sprites/441.png",
        "Spiritomb": "/images/sprites/442.png",
        "Gible": "/images/sprites/443.png",
        "Gabite": "/images/sprites/444.png",
        "Garchomp": "/images/sprites/445.png",
        "Munchlax": "/images/sprites/446.png",
        "Riolu": "/images/sprites/447.png",
        "Lucario": "/images/sprites/448.png",
        "Hippopotas": "/images/sprites/449.png",
        "Hippowdon": "/images/sprites/450.png",
        "Skorupi": "/images/sprites/451.png",
        "Drapion": "/images/sprites/452.png",
        "Croagunk": "/images/sprites/453.png",
        "Toxicroak": "/images/sprites/454.png",
        "Carnivine": "/images/sprites/455.png",
        "Finneon": "/images/sprites/456.png",
        "Lumineon": "/images/sprites/457.png",
        "Mantyke": "/images/sprites/458.png",
        "Snover": "/images/sprites/459.png",
        "Abomasnow": "/images/sprites/460.png",
        "Weavile": "/images/sprites/461.png",
        "Magnezone": "/images/sprites/462.png",
        "Lickilicky": "/images/sprites/463.png",
        "Rhyperior": "/images/sprites/464.png",
        "Tangrowth": "/images/sprites/465.png",
        "Electivire": "/images/sprites/466.png",
        "Magmortar": "/images/sprites/467.png",
        "Togekiss": "/images/sprites/468.png",
        "Yanmega": "/images/sprites/469.png",
        "Leafeon": "/images/sprites/470.png",
        "Glaceon": "/images/sprites/471.png",
        "Gliscor": "/images/sprites/472.png",
        "Mamoswine": "/images/sprites/473.png",
        "Porygon-Z": "/images/sprites/474.png",
        "Gallade": "/images/sprites/475.png",
        "Probopass": "/images/sprites/476.png",
        "Dusknoir": "/images/sprites/477.png",
        "Froslass": "/images/sprites/478.png",
        "Rotom": "/images/sprites/479.png",
        "Rotom (Heat)": "/images/sprites/479-h.png",
        "Rotom (Wash)": "/images/sprites/479-w.png",
        "Rotom (Frost)": "/images/sprites/479-fr.png",
        "Rotom (Fan)": "/images/sprites/479-fan.png",
        "Rotom (Mow)": "/images/sprites/479-m.png",
        "Uxie": "/images/sprites/480.png",
        "Mesprit": "/images/sprites/481.png",
        "Azelf": "/images/sprites/482.png",
        "Dialga": "/images/sprites/483.png",
        "Dialga (Origin)": "/images/sprites/483-o.png",
        "Palkia": "/images/sprites/484.png",
        "Palkia (Origin)": "/images/sprites/484-o.png",
        "Heatran": "/images/sprites/485.png",
        "Regigigas": "/images/sprites/486.png",
        "Giratina (Altered)": "/images/sprites/487-a.png",
        "Giratina (Origin)": "/images/sprites/487-o.png",
        "Cresselia": "/images/sprites/488.png",
        "Phione": "/images/sprites/489.png",
        "Manaphy": "/images/sprites/490.png",
        "Darkrai": "/images/sprites/491.png",
        "Shaymin (Land)": "/images/sprites/492-l.png",
        "Shaymin (Sky)": "/images/sprites/492-s.png",
        "Arceus": "/images/sprites/493.png",
        "Victini": "/images/sprites/494.png",
        "Snivy": "/images/sprites/495.png",
        "Servine": "/images/sprites/496.png",
        "Serperior": "/images/sprites/497.png",
        "Tepig": "/images/sprites/498.png",
        "Pignite": "/images/sprites/499.png",
        "Emboar": "/images/sprites/500.png",
        "Oshawott": "/images/sprites/501.png",
        "Dewott": "/images/sprites/502.png",
        "Samurott": "/images/sprites/503.png",
        "Samurott (Hisuian)": "/images/sprites/503-h.png",
        "Patrat": "/images/sprites/504.png",
        "Watchog": "/images/sprites/505.png",
        "Lillipup": "/images/sprites/506.png",
        "Herdier": "/images/sprites/507.png",
        "Stoutland": "/images/sprites/508.png",
        "Purrloin": "/images/sprites/509.png",
        "Liepard": "/images/sprites/510.png",
        "Pansage": "/images/sprites/511.png",
        "Simisage": "/images/sprites/512.png",
        "Pansear": "/images/sprites/513.png",
        "Simisear": "/images/sprites/514.png",
        "Panpour": "/images/sprites/515.png",
        "Simipour": "/images/sprites/516.png",
        "Munna": "/images/sprites/517.png",
        "Musharna": "/images/sprites/518.png",
        "Pidove": "/images/sprites/519.png",
        "Tranquill": "/images/sprites/520.png",
        "Unfezant": "/images/sprites/521.png",
        "Blitzle": "/images/sprites/522.png",
        "Zebstrika": "/images/sprites/523.png",
        "Roggenrola": "/images/sprites/524.png",
        "Boldore": "/images/sprites/525.png",
        "Gigalith": "/images/sprites/526.png",
        "Woobat": "/images/sprites/527.png",
        "Swoobat": "/images/sprites/528.png",
        "Drilbur": "/images/sprites/529.png",
        "Excadrill": "/images/sprites/530.png",
        "Audino": "/images/sprites/531.png",
        "Timburr": "/images/sprites/532.png",
        "Gurdurr": "/images/sprites/533.png",
        "Conkeldurr": "/images/sprites/534.png",
        "Tympole": "/images/sprites/535.png",
        "Palpitoad": "/images/sprites/536.png",
        "Seismitoad": "/images/sprites/537.png",
        "Throh": "/images/sprites/538.png",
        "Sawk": "/images/sprites/539.png",
        "Sewaddle": "/images/sprites/540.png",
        "Swadloon": "/images/sprites/541.png",
        "Leavanny": "/images/sprites/542.png",
        "Venipede": "/images/sprites/543.png",
        "Whirlipede": "/images/sprites/544.png",
        "Scolipede": "/images/sprites/545.png",
        "Cottonee": "/images/sprites/546.png",
        "Whimsicott": "/images/sprites/547.png",
        "Petilil": "/images/sprites/548.png",
        "Lilligant": "/images/sprites/549.png",
        "Lilligant (Hisuian)": "/images/sprites/549-h.png",
        "Basculin (Red-Striped)": "/images/sprites/550-r.png",
        "Basculin (Blue-Striped)": "/images/sprites/550-b.png",
        "Basculin (White-Striped)": "/images/sprites/550-w.png",
        "Sandile": "/images/sprites/551.png",
        "Krokorok": "/images/sprites/552.png",
        "Krookodile": "/images/sprites/553.png",
        "Darumaka": "/images/sprites/554.png",
        "Darumaka (Galarian)": "/images/sprites/554-g.png",
        "Darmanitan (Standard)": "/images/sprites/555.png",
        "Darmanitan (Zen)": "/images/sprites/555-zen.png",
        "Darmanitan (Galarian Standard)": "/images/sprites/555-g.png",
        "Darmanitan (Galarian Zen)": "/images/sprites/555-gz.png",
        "Maractus": "/images/sprites/556.png",
        "Dwebble": "/images/sprites/557.png",
        "Crustle": "/images/sprites/558.png",
        "Scraggy": "/images/sprites/559.png",
        "Scrafty": "/images/sprites/560.png",
        "Sigilyph": "/images/sprites/561.png",
        "Yamask": "/images/sprites/562.png",
        "Yamask (Galarian)": "/images/sprites/562-g.png",
        "Cofagrigus": "/images/sprites/563.png",
        "Tirtouga": "/images/sprites/564.png",
        "Carracosta": "/images/sprites/565.png",
        "Archen": "/images/sprites/566.png",
        "Archeops": "/images/sprites/567.png",
        "Trubbish": "/images/sprites/568.png",
        "Garbodor": "/images/sprites/569.png",
        "Zorua": "/images/sprites/570.png",
        "Zorua (Hisuian)": "/images/sprites/570-h.png",
        "Zoroark": "/images/sprites/571.png",
        "Zoroark (Hisuian)": "/images/sprites/571-h.png",
        "Minccino": "/images/sprites/572.png",
        "Cinccino": "/images/sprites/573.png",
        "Gothita": "/images/sprites/574.png",
        "Gothorita": "/images/sprites/575.png",
        "Gothitelle": "/images/sprites/576.png",
        "Solosis": "/images/sprites/577.png",
        "Duosion": "/images/sprites/578.png",
        "Reuniclus": "/images/sprites/579.png",
        "Ducklett": "/images/sprites/580.png",
        "Swanna": "/images/sprites/581.png",
        "Vanillite": "/images/sprites/582.png",
        "Vanillish": "/images/sprites/583.png",
        "Vanilluxe": "/images/sprites/584.png",
        "Deerling": "/images/sprites/585.png",
        "Sawsbuck": "/images/sprites/586.png",
        "Emolga": "/images/sprites/587.png",
        "Karrablast": "/images/sprites/588.png",
        "Escavalier": "/images/sprites/589.png",
        "Foongus": "/images/sprites/590.png",
        "Amoonguss": "/images/sprites/591.png",
        "Frillish": "/images/sprites/592.png",
        "Jellicent": "/images/sprites/593.png",
        "Alomomola": "/images/sprites/594.png",
        "Joltik": "/images/sprites/595.png",
        "Galvantula": "/images/sprites/596.png",
        "Ferroseed": "/images/sprites/597.png",
        "Ferrothorn": "/images/sprites/598.png",
        "Klink": "/images/sprites/599.png",
        "Klang": "/images/sprites/600.png",
        "Klinklang": "/images/sprites/601.png",
        "Tynamo": "/images/sprites/602.png",
        "Eelektrik": "/images/sprites/603.png",
        "Eelektross": "/images/sprites/604.png",
        "Elgyem": "/images/sprites/605.png",
        "Beheeyem": "/images/sprites/606.png",
        "Litwick": "/images/sprites/607.png",
        "Lampent": "/images/sprites/608.png",
        "Chandelure": "/images/sprites/609.png",
        "Axew": "/images/sprites/610.png",
        "Fraxure": "/images/sprites/611.png",
        "Haxorus": "/images/sprites/612.png",
        "Cubchoo": "/images/sprites/613.png",
        "Beartic": "/images/sprites/614.png",
        "Cryogonal": "/images/sprites/615.png",
        "Shelmet": "/images/sprites/616.png",
        "Accelgor": "/images/sprites/617.png",
        "Stunfisk": "/images/sprites/618.png",
        "Stunfisk (Galarian)": "/images/sprites/618-g.png",
        "Mienfoo": "/images/sprites/619.png",
        "Mienshao": "/images/sprites/620.png",
        "Druddigon": "/images/sprites/621.png",
        "Golett": "/images/sprites/622.png",
        "Golurk": "/images/sprites/623.png",
        "Pawniard": "/images/sprites/624.png",
        "Bisharp": "/images/sprites/625.png",
        "Bouffalant": "/images/sprites/626.png",
        "Rufflet": "/images/sprites/627.png",
        "Braviary": "/images/sprites/628.png",
        "Braviary (Hisuian)": "/images/sprites/628-h.png",
        "Vullaby": "/images/sprites/629.png",
        "Mandibuzz": "/images/sprites/630.png",
        "Heatmor": "/images/sprites/631.png",
        "Durant": "/images/sprites/632.png",
        "Deino": "/images/sprites/633.png",
        "Zweilous": "/images/sprites/634.png",
        "Hydreigon": "/images/sprites/635.png",
        "Larvesta": "/images/sprites/636.png",
        "Volcarona": "/images/sprites/637.png",
        "Cobalion": "/images/sprites/638.png",
        "Terrakion": "/images/sprites/639.png",
        "Virizion": "/images/sprites/640.png",
        "Tornadus (Incarnate)": "/images/sprites/641.png",
        "Tornadus (Therian)": "/images/sprites/641-t.png",
        "Thundurus (Incarnate)": "/images/sprites/642.png",
        "Thundurus (Therian)": "/images/sprites/642-t.png",
        "Reshiram": "/images/sprites/643.png",
        "Zekrom": "/images/sprites/644.png",
        "Landorus (Incarnate)": "/images/sprites/645.png",
        "Landorus (Therian)": "/images/sprites/645-t.png",
        "Kyurem": "/images/sprites/646.png",
        "Kyurem (White)": "/images/sprites/646-w.png",
        "Kyurem (Black)": "/images/sprites/646-b.png",
        "Keldeo (Resolute)": "/images/sprites/647.png",
        "Meloetta (Aria)": "/images/sprites/648-a.png",
        "Meloetta (Pirouette)": "/images/sprites/648-p.png",
        "Genesect": "/images/sprites/649.png",
        "Chespin": "/images/sprites/650.png",
        "Quilladin": "/images/sprites/651.png",
        "Chesnaught": "/images/sprites/652.png",
        "Fennekin": "/images/sprites/653.png",
        "Braixen": "/images/sprites/654.png",
        "Delphox": "/images/sprites/655.png",
        "Froakie": "/images/sprites/656.png",
        "Frogadier": "/images/sprites/657.png",
        "Greninja": "/images/sprites/658.png",
        "Greninja (Ash)": "/images/sprites/658-a.png",
        "Bunnelby": "/images/sprites/659.png",
        "Diggersby": "/images/sprites/660.png",
        "Fletchling": "/images/sprites/661.png",
        "Fletchinder": "/images/sprites/662.png",
        "Talonflame": "/images/sprites/663.png",
        "Scatterbug": "/images/sprites/664.png",
        "Spewpa": "/images/sprites/665.png",
        "Vivillon": "/images/sprites/666.png",
        "Litleo": "/images/sprites/667.png",
        "Pyroar": "/images/sprites/668.png",
        "Flabebe": "/images/sprites/669.png",
        "Floette": "/images/sprites/670.png",
        "Florges": "/images/sprites/671.png",
        "Skiddo": "/images/sprites/672.png",
        "Gogoat": "/images/sprites/673.png",
        "Pancham": "/images/sprites/674.png",
        "Pangoro": "/images/sprites/675.png",
        "Furfrou": "/images/sprites/676.png",
        "Espurr": "/images/sprites/677.png",
        "Meowstic (Male)": "/images/sprites/678-m.png",
        "Meowstic (Female)": "/images/sprites/678-f.png",
        "Honedge": "/images/sprites/679.png",
        "Doublade": "/images/sprites/680.png",
        "Aegislash (Shield)": "/images/sprites/681-s.png",
        "Aegislash (Blade)": "/images/sprites/681-b.png",
        "Spritzee": "/images/sprites/682.png",
        "Aromatisse": "/images/sprites/683.png",
        "Swirlix": "/images/sprites/684.png",
        "Slurpuff": "/images/sprites/685.png",
        "Inkay": "/images/sprites/686.png",
        "Malamar": "/images/sprites/687.png",
        "Binacle": "/images/sprites/688.png",
        "Barbaracle": "/images/sprites/689.png",
        "Skrelp": "/images/sprites/690.png",
        "Dragalge": "/images/sprites/691.png",
        "Clauncher": "/images/sprites/692.png",
        "Clawitzer": "/images/sprites/693.png",
        "Helioptile": "/images/sprites/694.png",
        "Heliolisk": "/images/sprites/695.png",
        "Tyrunt": "/images/sprites/696.png",
        "Tyrantrum": "/images/sprites/697.png",
        "Amaura": "/images/sprites/698.png",
        "Aurorus": "/images/sprites/699.png",
        "Sylveon": "/images/sprites/700.png",
        "Hawlucha": "/images/sprites/701.png",
        "Dedenne": "/images/sprites/702.png",
        "Carbink": "/images/sprites/703.png",
        "Goomy": "/images/sprites/704.png",
        "Sliggoo": "/images/sprites/705.png",
        "Sliggoo (Hisuian)": "/images/sprites/705-h.png",
        "Goodra": "/images/sprites/706.png",
        "Goodra (Hisuian)": "/images/sprites/706-h.png",
        "Klefki": "/images/sprites/707.png",
        "Phantump": "/images/sprites/708.png",
        "Trevenant": "/images/sprites/709.png",
        "Pumpkaboo (Average)": "/images/sprites/710-a.png",
        "Pumpkaboo (Small)": "/images/sprites/710-sm.png",
        "Pumpkaboo (Large)": "/images/sprites/710-l.png",
        "Pumpkaboo (Super)": "/images/sprites/710-su.png",
        "Gourgeist (Average)": "/images/sprites/711-a.png",
        "Gourgeist (Small)": "/images/sprites/711-sm.png",
        "Gourgeist (Large)": "/images/sprites/711-l.png",
        "Gourgeist (Super)": "/images/sprites/711-su.png",
        "Bergmite": "/images/sprites/712.png",
        "Avalugg": "/images/sprites/713.png",
        "Avalugg (Hisuian)": "/images/sprites/713-h.png",
        "Noibat": "/images/sprites/714.png",
        "Noivern": "/images/sprites/715.png",
        "Xerneas": "/images/sprites/716.png",
        "Yveltal": "/images/sprites/717.png",
        "Zygarde (50%)": "/images/sprites/718-50.png",
        "Zygarde (10%)": "/images/sprites/718-10.png",
        "Zygarde (Complete)": "/images/sprites/718.png",
        "Diancie": "/images/sprites/719.png",
        "Hoopa (Confined)": "/images/sprites/720-c.png",
        "Hoopa (Unbound)": "/images/sprites/720-u.png",
        "Volcanion": "/images/sprites/721.png",
        "Rowlet": "/images/sprites/722.png",
        "Dartrix": "/images/sprites/723.png",
        "Decidueye": "/images/sprites/724.png",
        "Decidueye (Hisuian)": "/images/sprites/724-h.png",
        "Litten": "/images/sprites/725.png",
        "Torracat": "/images/sprites/726.png",
        "Incineroar": "/images/sprites/727.png",
        "Popplio": "/images/sprites/728.png",
        "Brionne": "/images/sprites/729.png",
        "Primarina": "/images/sprites/730.png",
        "Pikipek": "/images/sprites/731.png",
        "Trumbeak": "/images/sprites/732.png",
        "Toucannon": "/images/sprites/733.png",
        "Yungoos": "/images/sprites/734.png",
        "Gumshoos": "/images/sprites/735.png",
        "Grubbin": "/images/sprites/736.png",
        "Charjabug": "/images/sprites/737.png",
        "Vikavolt": "/images/sprites/738.png",
        "Crabrawler": "/images/sprites/739.png",
        "Crabominable": "/images/sprites/740.png",
        "Oricorio (Baile)": "/images/sprites/741-b.png",
        "Oricorio (Pom-Pom)": "/images/sprites/741-po.png",
        "Oricorio (Pau)": "/images/sprites/741-pau.png",
        "Oricorio (Sensu)": "/images/sprites/741-s.png",
        "Cutiefly": "/images/sprites/742.png",
        "Ribombee": "/images/sprites/743.png",
        "Rockruff": "/images/sprites/744.png",
        "Lycanroc (Midday)": "/images/sprites/745-md.png",
        "Lycanroc (Midnight)": "/images/sprites/745-mn.png",
        "Lycanroc (Dusk)": "/images/sprites/745-d.png",
        "Wishiwashi (Solo)": "/images/sprites/746.png",
        "Wishiwashi (School)": "/images/sprites/746-sch.png",
        "Mareanie": "/images/sprites/747.png",
        "Toxapex": "/images/sprites/748.png",
        "Mudbray": "/images/sprites/749.png",
        "Mudsdale": "/images/sprites/750.png",
        "Dewpider": "/images/sprites/751.png",
        "Araquanid": "/images/sprites/752.png",
        "Fomantis": "/images/sprites/753.png",
        "Lurantis": "/images/sprites/754.png",
        "Morelull": "/images/sprites/755.png",
        "Shiinotic": "/images/sprites/756.png",
        "Salandit": "/images/sprites/757.png",
        "Salazzle": "/images/sprites/758.png",
        "Stufful": "/images/sprites/759.png",
        "Bewear": "/images/sprites/760.png",
        "Bounsweet": "/images/sprites/761.png",
        "Steenee": "/images/sprites/762.png",
        "Tsareena": "/images/sprites/763.png",
        "Comfey": "/images/sprites/764.png",
        "Oranguru": "/images/sprites/765.png",
        "Passimian": "/images/sprites/766.png",
        "Wimpod": "/images/sprites/767.png",
        "Golisopod": "/images/sprites/768.png",
        "Sandygast": "/images/sprites/769.png",
        "Palossand": "/images/sprites/770.png",
        "Pyukumuku": "/images/sprites/771.png",
        "Type: Null": "/images/sprites/772.png",
        "Silvally": "/images/sprites/773.png",
        "Minior (Meteor)": "/images/sprites/774.png",
        "Minior (Core)": "/images/sprites/774-c.png",
        "Komala": "/images/sprites/775.png",
        "Turtonator": "/images/sprites/776.png",
        "Togedemaru": "/images/sprites/777.png",
        "Mimikyu": "/images/sprites/778.png",
        "Bruxish": "/images/sprites/779.png",
        "Drampa": "/images/sprites/780.png",
        "Dhelmise": "/images/sprites/781.png",
        "Jangmo-o": "/images/sprites/782.png",
        "Hakamo-o": "/images/sprites/783.png",
        "Kommo-o": "/images/sprites/784.png",
        "Tapu Koko": "/images/sprites/785.png",
        "Tapu Lele": "/images/sprites/786.png",
        "Tapu Bulu": "/images/sprites/787.png",
        "Tapu Fini": "/images/sprites/788.png",
        "Cosmog": "/images/sprites/789.png",
        "Cosmoem": "/images/sprites/790.png",
        "Solgaleo": "/images/sprites/791.png",
        "Lunala": "/images/sprites/792.png",
        "Nihilego": "/images/sprites/793.png",
        "Buzzwole": "/images/sprites/794.png",
        "Pheromosa": "/images/sprites/795.png",
        "Xurkitree": "/images/sprites/796.png",
        "Celesteela": "/images/sprites/797.png",
        "Kartana": "/images/sprites/798.png",
        "Guzzlord": "/images/sprites/799.png",
        "Necrozma": "/images/sprites/800.png",
        "Necrozma (Dusk Mane)": "/images/sprites/800-dm.png",
        "Necrozma (Dawn Wings)": "/images/sprites/800-dw.png",
        "Necrozma (Ultra)": "/images/sprites/800-u.png",
        "Magearna": "/images/sprites/801.png",
        "Marshadow": "/images/sprites/802.png",
        "Poipole": "/images/sprites/803.png",
        "Naganadel": "/images/sprites/804.png",
        "Stakataka": "/images/sprites/805.png",
        "Blacephalon": "/images/sprites/806.png",
        "Zeraora": "/images/sprites/807.png",
        "Meltan": "/images/sprites/808.png",
        "Melmetal": "/images/sprites/809.png",
        "Grookey": "/images/sprites/810.png",
        "Thwackey": "/images/sprites/811.png",
        "Rillaboom": "/images/sprites/812.png",
        "Scorbunny": "/images/sprites/813.png",
        "Raboot": "/images/sprites/814.png",
        "Cinderace": "/images/sprites/815.png",
        "Sobble": "/images/sprites/816.png",
        "Drizzile": "/images/sprites/817.png",
        "Inteleon": "/images/sprites/818.png",
        "Skwovet": "/images/sprites/819.png",
        "Greedent": "/images/sprites/820.png",
        "Rookidee": "/images/sprites/821.png",
        "Corvisquire": "/images/sprites/822.png",
        "Corviknight": "/images/sprites/823.png",
        "Blipbug": "/images/sprites/824.png",
        "Dottler": "/images/sprites/825.png",
        "Orbeetle": "/images/sprites/826.png",
        "Nickit": "/images/sprites/827.png",
        "Thievul": "/images/sprites/828.png",
        "Gossifleur": "/images/sprites/829.png",
        "Eldegoss": "/images/sprites/830.png",
        "Wooloo": "/images/sprites/831.png",
        "Dubwool": "/images/sprites/832.png",
        "Chewtle": "/images/sprites/833.png",
        "Drednaw": "/images/sprites/834.png",
        "Yamper": "/images/sprites/835.png",
        "Boltund": "/images/sprites/836.png",
        "Rolycoly": "/images/sprites/837.png",
        "Carkol": "/images/sprites/838.png",
        "Coalossal": "/images/sprites/839.png",
        "Applin": "/images/sprites/840.png",
        "Flapple": "/images/sprites/841.png",
        "Appletun": "/images/sprites/842.png",
        "Silicobra": "/images/sprites/843.png",
        "Sandaconda": "/images/sprites/844.png",
        "Cramorant": "/images/sprites/845.png",
        "Arrokuda": "/images/sprites/846.png",
        "Barraskewda": "/images/sprites/847.png",
        "Toxel": "/images/sprites/848.png",
        "Toxtricity (Amped)": "/images/sprites/849-a.png",
        "Toxtricity (Low Key)": "/images/sprites/849-l.png",
        "Sizzlipede": "/images/sprites/850.png",
        "Centiskorch": "/images/sprites/851.png",
        "Clobbopus": "/images/sprites/852.png",
        "Grapploct": "/images/sprites/853.png",
        "Sinistea": "/images/sprites/854.png",
        "Polteageist": "/images/sprites/855.png",
        "Hatenna": "/images/sprites/856.png",
        "Hattrem": "/images/sprites/857.png",
        "Hatterene": "/images/sprites/858.png",
        "Impidimp": "/images/sprites/859.png",
        "Morgrem": "/images/sprites/860.png",
        "Grimmsnarl": "/images/sprites/861.png",
        "Obstagoon": "/images/sprites/862.png",
        "Perrserker": "/images/sprites/863.png",
        "Cursola": "/images/sprites/864.png",
        "Sirfetchd": "/images/sprites/865.png",
        "Mr. Rime": "/images/sprites/866.png",
        "Runerigus": "/images/sprites/867.png",
        "Milcery": "/images/sprites/868.png",
        "Alcremie": "/images/sprites/869.png",
        "Falinks": "/images/sprites/870.png",
        "Pincurchin": "/images/sprites/871.png",
        "Snom": "/images/sprites/872.png",
        "Frosmoth": "/images/sprites/873.png",
        "Stonjourner": "/images/sprites/874.png",
        "Eiscue (Ice)": "/images/sprites/875-i.png",
        "Eiscue (Noice)": "/images/sprites/875-n.png",
        "Indeedee (Male)": "/images/sprites/876-m.png",
        "Indeedee (Female)": "/images/sprites/876-f.png",
        "Morpeko (Full Belly)": "/images/sprites/877-f.png",
        "Morpeko (Hangry)": "/images/sprites/877-h.png",
        "Cufant": "/images/sprites/878.png",
        "Copperajah": "/images/sprites/879.png",
        "Dracozolt": "/images/sprites/880.png",
        "Arctozolt": "/images/sprites/881.png",
        "Dracovish": "/images/sprites/882.png",
        "Arctovish": "/images/sprites/883.png",
        "Duraludon": "/images/sprites/884.png",
        "Dreepy": "/images/sprites/885.png",
        "Drakloak": "/images/sprites/886.png",
        "Dragapult": "/images/sprites/887.png",
        "Zacian (Hero of Many Battles)": "/images/sprites/888.png",
        "Zacian (Crowned Sword)": "/images/sprites/888-c.png",
        "Zamazenta (Hero of Many Battles)": "/images/sprites/889.png",
        "Zamazenta (Crowned Shield)": "/images/sprites/889-c.png",
        "Eternatus": "/images/sprites/890.png",
        "Kubfu": "/images/sprites/891.png",
        "Urshifu (Single Strike)": "/images/sprites/892-s.png",
        "Urshifu (Rapid Strike)": "/images/sprites/892-r.png",
        "Zarude": "/images/sprites/893.png",
        "Regieleki": "/images/sprites/894.png",
        "Regidrago": "/images/sprites/895.png",
        "Glastrier": "/images/sprites/896.png",
        "Spectrier": "/images/sprites/897.png",
        "Calyrex": "/images/sprites/898.png",
        "Calyrex (Ice Rider)": "/images/sprites/898-i.png",
        "Calyrex (Shadow Rider)": "/images/sprites/898-s.png",
        "Wyrdeer": "/images/sprites/899.png",
        "Kleavor": "/images/sprites/900.png",
        "Ursaluna": "/images/sprites/901.png",
        "Basculegion (Male)": "/images/sprites/902-m.png",
        "Basculegion (Female)": "/images/sprites/902-f.png",
        "Sneasler": "/images/sprites/903.png",
        "Overqwil": "/images/sprites/904.png",
        "Enamorus (Incarnate)": "/images/sprites/905-i.png",
        "Enamorus (Therian)": "/images/sprites/905-t.png",
        "Sprigatito": "/images/sprites/906.png",
        "Floragato": "/images/sprites/907.png",
        "Meowscarada": "/images/sprites/908.png",
        "Fuecoco": "/images/sprites/909.png",
        "Crocalor": "/images/sprites/910.png",
        "Skeledirge": "/images/sprites/911.png",
        "Quaxly": "/images/sprites/912.png",
        "Quaxwell": "/images/sprites/913.png",
        "Quaquaval": "/images/sprites/914.png",
        "Lechonk": "/images/sprites/915.png",
        "Oinkologne (Male)": "/images/sprites/916-m.png",
        "Oinkologne (Female)": "/images/sprites/916-f.png",
        "Tarountula": "/images/sprites/917.png",
        "Spidops": "/images/sprites/918.png",
        "Nymble": "/images/sprites/919.png",
        "Lokix": "/images/sprites/920.png",
        "Pawmi": "/images/sprites/921.png",
        "Pawmo": "/images/sprites/922.png",
        "Pawmot": "/images/sprites/923.png",
        "Tandemaus": "/images/sprites/924.png",
        "Maushold (Family of Four)": "/images/sprites/925-4.png",
        "Maushold (Family of Three)": "/images/sprites/925-3.png",
        "Fidough": "/images/sprites/926.png",
        "Dachsbun": "/images/sprites/927.png",
        "Smoliv": "/images/sprites/928.png",
        "Dolliv": "/images/sprites/929.png",
        "Arboliva": "/images/sprites/930.png",
        "Squawkabilly (Green)": "/images/sprites/931-g.png",
        "Squawkabilly (Blue)": "/images/sprites/931-b.png",
        "Squawkabilly (Yellow)": "/images/sprites/931-y.png",
        "Squawkabilly (White)": "/images/sprites/931-w.png",
        "Nacli": "/images/sprites/932.png",
        "Naclstack": "/images/sprites/933.png",
        "Garganacl": "/images/sprites/934.png",
        "Charcadet": "/images/sprites/935.png",
        "Armarouge": "/images/sprites/936.png",
        "Ceruledge": "/images/sprites/937.png",
        "Tadbulb": "/images/sprites/938.png",
        "Bellibolt": "/images/sprites/939.png",
        "Wattrel": "/images/sprites/940.png",
        "Kilowattrel": "/images/sprites/941.png",
        "Maschiff": "/images/sprites/942.png",
        "Mabosstiff": "/images/sprites/943.png",
        "Shroodle": "/images/sprites/944.png",
        "Grafaiai": "/images/sprites/945.png",
        "Bramblin": "/images/sprites/946.png",
        "Brambleghast": "/images/sprites/947.png",
        "Toedscool": "/images/sprites/948.png",
        "Toedscruel": "/images/sprites/949.png",
        "Klawf": "/images/sprites/950.png",
        "Capsakid": "/images/sprites/951.png",
        "Scovillain": "/images/sprites/952.png",
        "Rellor": "/images/sprites/953.png",
        "Rabsca": "/images/sprites/954.png",
        "Flittle": "/images/sprites/955.png",
        "Espathra": "/images/sprites/956.png",
        "Tinkatink": "/images/sprites/957.png",
        "Tinkatuff": "/images/sprites/958.png",
        "Tinkaton": "/images/sprites/959.png",
        "Wiglett": "/images/sprites/960.png",
        "Wugtrio": "/images/sprites/961.png",
        "Bombirdier": "/images/sprites/962.png",
        "Finizen": "/images/sprites/963.png",
        "Palafin (Zero)": "/images/sprites/964-z.png",
        "Palafin (Hero)": "/images/sprites/964-h.png",
        "Varoom": "/images/sprites/965.png",
        "Revavroom": "/images/sprites/966.png",
        "Cyclizar": "/images/sprites/967.png",
        "Orthworm": "/images/sprites/968.png",
        "Glimmet": "/images/sprites/969.png",
        "Glimmora": "/images/sprites/970.png",
        "Greavard": "/images/sprites/971.png",
        "Houndstone": "/images/sprites/972.png",
        "Flamigo": "/images/sprites/973.png",
        "Cetoddle": "/images/sprites/974.png",
        "Cetitan": "/images/sprites/975.png",
        "Veluza": "/images/sprites/976.png",
        "Dondozo": "/images/sprites/977.png",
        "Tatsugiri (Curly)": "/images/sprites/978-c.png",
        "Tatsugiri (Droopy)": "/images/sprites/978-d.png",
        "Tatsugiri (Stretchy)": "/images/sprites/978-s.png",
        "Annihilape": "/images/sprites/979.png",
        "Clodsire": "/images/sprites/980.png",
        "Farigiraf": "/images/sprites/981.png",
        "Dudunsparce (Two-Segment)": "/images/sprites/982-2.png",
        "Dudunsparce (Three-Segment)": "/images/sprites/982-3.png",
        "Kingambit": "/images/sprites/983.png",
        "Great Tusk": "/images/sprites/984.png",
        "Scream Tail": "/images/sprites/985.png",
        "Brute Bonnet": "/images/sprites/986.png",
        "Flutter Mane": "/images/sprites/987.png",
        "Slither Wing": "/images/sprites/988.png",
        "Sandy Shocks": "/images/sprites/989.png",
        "Iron Treads": "/images/sprites/990.png",
        "Iron Bundle": "/images/sprites/991.png",
        "Iron Hands": "/images/sprites/992.png",
        "Iron Jugulis": "/images/sprites/993.png",
        "Iron Moth": "/images/sprites/994.png",
        "Iron Thorns": "/images/sprites/995.png",
        "Frigibax": "/images/sprites/996.png",
        "Arctibax": "/images/sprites/997.png",
        "Baxcalibur": "/images/sprites/998.png",
        "Gimmighoul": "/images/sprites/999.png",
        "Gholdengo": "/images/sprites/1000.png",
        "Wo-Chien": "/images/sprites/1001.png",
        "Chien-Pao": "/images/sprites/1002.png",
        "Ting-Lu": "/images/sprites/1003.png",
        "Chi-Yu": "/images/sprites/1004.png",
        "Roaring Moon": "/images/sprites/1005.png",
        "Iron Valiant": "/images/sprites/1006.png",
        "Koraidon": "/images/sprites/1007.png",
        "Miraidon": "/images/sprites/1008.png",
        "Walking Wake": "/images/sprites/1009.png",
        "Iron Leaves": "/images/sprites/1010.png"
    }});
});
